# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-24 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What was purchased or deducted from the main account', max_length=200)),
                ('account_number', models.PositiveIntegerField(help_text='Account Number')),
            ],
        ),
        migrations.CreateModel(
            name='CrudeType',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Products', primary_key=True, serialize=False)),
                ('crude_type', models.CharField(blank=True, choices=[('PMS', 'Petrol'), ('DPK', 'Diesels'), ('AGO', 'Kerosene'), ('GAS', 'Natural Gas')], default='PMS', help_text='Select the Crude product', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('amount', models.CharField(help_text='Amount Deposited', max_length=200)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='OnAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OnAccountSale',
            fields=[
                ('account_sale', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('date_purchased', models.DateField()),
                ('on_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.OnAccount')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('pump_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('crude_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CrudeType')),
            ],
        ),
        migrations.CreateModel(
            name='PumpSale',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=9)),
                ('closing', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Stations', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StationPump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Pump')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('tank_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Tanks', primary_key=True, serialize=False)),
                ('tank', models.CharField(max_length=200)),
                ('crude_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CrudeType')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station')),
            ],
        ),
        migrations.CreateModel(
            name='TankQuantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.PositiveIntegerField()),
                ('closing', models.PositiveIntegerField()),
                ('under', models.PositiveIntegerField()),
                ('pump', models.DecimalField(decimal_places=2, max_digits=6)),
                ('new', models.PositiveIntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now=True)),
                ('tank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='What was purchased or deducted from the main account', max_length=200)),
                ('value', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now=True)),
                ('date_used', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stationpump',
            name='tank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Tank'),
        ),
        migrations.AddField(
            model_name='pumpsale',
            name='pump',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.StationPump'),
        ),
        migrations.AddField(
            model_name='pumpsale',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station'),
        ),
        migrations.AddField(
            model_name='onaccountsale',
            name='station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station'),
        ),
        migrations.AddField(
            model_name='depositamount',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PumpSale'),
        ),
        migrations.AlterUniqueTogether(
            name='tank',
            unique_together=set([('station', 'tank')]),
        ),
        migrations.AlterUniqueTogether(
            name='stationpump',
            unique_together=set([('station', 'pump')]),
        ),
        migrations.AlterUniqueTogether(
            name='pump',
            unique_together=set([('crude_type', 'name')]),
        ),
    ]
