# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What was purchased or deducted from the main account', max_length=200)),
                ('account_number', models.PositiveIntegerField(help_text='Account Number')),
            ],
        ),
        migrations.CreateModel(
            name='CrudeType',
            fields=[
                ('product_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Products', primary_key=True, serialize=False)),
                ('crude_type', models.CharField(blank=True, choices=[('PMS', 'Petrol'), ('DPK', 'Diesels'), ('AGO', 'Kerosene'), ('GAS', 'Natural Gas')], default='PMS', help_text='Select the Crude product', max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OnAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Stations', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
