# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-29 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170629_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('amount', models.CharField(help_text='Amount Deposited', max_length=200)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BankAccount')),
            ],
        ),
        migrations.CreateModel(
            name='OnAccountSale',
            fields=[
                ('account_sale', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('date_purchased', models.DateField()),
                ('on_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.OnAccount')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station')),
            ],
        ),
        migrations.CreateModel(
            name='PumpSale',
            fields=[
                ('sale_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for Pumps', primary_key=True, serialize=False)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=9)),
                ('closing', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sale_add_date', models.DateField(auto_now=True)),
                ('date_purchased', models.DateField(blank=True, null=True)),
                ('pump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.StationPump')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Station')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(help_text='What was purchased or deducted from the main account', max_length=200)),
                ('value', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now=True)),
                ('date_used', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='depositamount',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.PumpSale'),
        ),
    ]
