# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170629_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
